name: test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: macos-latest
    strategy:
      matrix:
        version: ['3.9', '3.10.0', '3.10.1']

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}

      - name: test
        run: python -c 'import tkinter'

