name: test2

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: test2
    runs-on: macos-latest
    # runs-on: macos-10.15
    strategy:
      matrix:
        version: ['3.9', '3.10.1']

    steps:
      - uses: actions/checkout@v2

      # - name: Setup Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: ${{ matrix.version }}

      - name: test env
        run: |
          which brew
          which port

      # - name: Setup Python
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install python3 python3-pip python3-pytest python3-tk tk-dev
      #     ls /usr/bin
      #     sudo rm /usr/bin/python
      #     # sudo ln -s /usr/bin/pyto

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          # pip install tk

      - name: Test tk
        run: python -c 'import tkinter'

